const buttonColour = ["red", "blue", "green", "yellow"];
const gamePattern = []; //array to store the colour sequence generated by game.
const userClickedPattern = []; //array to store the colour sequence generated by user.

var started = false; //key to check wether keypress is active or buttons are active.
var level = 1; //game level


//wait for user to inticate the game by pressing a random key.
$(document).on("keypress", function nextSequence() {
  if (started === false) { //check keypress is active.
    $("#level-title").text("Level " + level);
    newSequence(); //call to generate the sequence.
    started = true; //inactivate keypress and activate buttons.
  }
});


//function to generate colour sequence.
function newSequence() {
  var randomNumber = Math.floor(Math.random()*4); //genrate a random number.
  var randomChosenColour = buttonColour[randomNumber]; //choosing a random color corresponding to generated random number from colour array.
  gamePattern.push(randomChosenColour);
  setTimeout(function(){
    $("#" + randomChosenColour).fadeOut(100).fadeIn(100);
    playSound(randomChosenColour);
  }, 500); //added a delay between two levels.
};


//taking user response and campare with generated colour sequence.
var numberOfUserClicks = 0;
$(".btn").on("click", function(event) { //adding event listener
  if (started === true) { //check button is active.
    var userChosenColour = $(this).attr("id");
    userClickedPattern.push(userChosenColour);
    playSound(userChosenColour);
    animatePress(userChosenColour);//animating the clicked button.
    numberOfUserClicks = numberOfUserClicks + 1;//

    if (userClickedPattern[numberOfUserClicks-1] === gamePattern[numberOfUserClicks-1]) {
      if (numberOfUserClicks === gamePattern.length) {
        level = level + 1;
        $("#level-title").text("Level " + level);
        userClickedPattern.splice(0, userClickedPattern.length);
        numberOfUserClicks = 0;
        newSequence();
      }
    } else {
      started = false;//inactivating buttons and active keypress.
      $("#level-title").text("Game Over, Press Any Key to Restart");
      $("body").addClass("game-over");
      setTimeout(function() {
        $("body").removeClass("game-over");
      }, 100);
      var gameOverSound = new Audio("sounds/wrong.mp3");
      gameOverSound.play();
      userClickedPattern.splice(0, userClickedPattern.length);
      numberOfUserClicks = 0;
      gamePattern.splice(0, gamePattern.length);
      level = 0;
    }
  }
});




//functions used into the higer oder functions.

//animating button pressed by user.
function animatePress(currentColor) {
  $("#" + currentColor).addClass("pressed");
  setTimeout(function() {
    $("#" + currentColor).removeClass("pressed");
  }, 100);
}
//playing the sound of pressed button.
function playSound(name) {
  var clickSound = new Audio("sounds/" + name + ".mp3");
  clickSound.play();
};
